# Generated by Django 5.2.3 on 2025-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('aspirante', models.CharField(max_length=100)),
            ],
        ),
    ]
